# Generated by Django 4.0.6 on 2023-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('sold', 'sold'), ('rental', 'rental')], max_length=50, null=True),
        ),
    ]
